name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: revraymondbaguma/wizard-chat:${{ github.sha }}

      - name: Show Docker version
        run: |
          docker run --rm revraymondbaguma/wizard-chat:${{ github.sha }} sh -c 'echo "Docker version: $(docker version --format "{{.Server.Version}}")"'

      - name: Cleanup
        run: |
          docker image prune -af
          docker container prune -f
